### ISSUE TITLE
Adding a custom action node to my custom behavior tree

### ISSUE THREAD

**Issue by AshBastian** [ros-navigation/docs.nav2.org#592]
Hello,
after the great help with the how to load a custom behavior tree, I'm now facing the problem of registering my own action nodes, so that the nav2 behavior tree can see them. I tried to do it like in the tutorial on the nav2 page (https://docs.nav2.org/plugin_tutorials/docs/writing_new_bt_plugin.html) but I'm unable to do it like that.

So now I would really appreciate some help on how to do it. My Code for my test plugin is below and I'm using Ubuntu 22.04 and ROS2 Humble. The file are named test.cpp, test.hpp and own_behavior_tree.xml

I can build the plugin without any problems and also source it to my project, but as soon as my launch file reaches the point of loading the behavior tree, is freezes into an endless loop.

```
<root main_tree_to_execute="MainTree">
  <BehaviorTree ID="MainTree">
    <MyCustomAction input_data="Hello World!" />
  </BehaviorTree>
</root>
```
```
#ifndef MY_NAV2_BT_PLUGIN__MY_CUSTOM_ACTION_NODE_HPP_
#define MY_NAV2_BT_PLUGIN__MY_CUSTOM_ACTION_NODE_HPP_

#include "behaviortree_cpp_v3/action_node.h"

namespace my_nav2_bt_plugin
{
  class MyCustomAction : public BT::SyncActionNode
  {
  public:
    MyCustomAction(const std::string &name, const BT::NodeConfiguration &config)
      : BT::SyncActionNode(name, config) {}

    // Method required by BehaviorTree.CPP library
    static BT::PortsList providedPorts()
    {
      return { BT::InputPort<std::string>("input_data") };
    }

    // Main method where the action is executed
    BT::NodeStatus tick() override
    {
      std::string input_data;
      if (!getInput<std::string>("input_data", input_data)) {
        throw BT::RuntimeError("missing required input [input_data]");
      }

      // Your custom logic here
      std::cout << "Custom action node: " << input_data << std::endl;

      return BT::NodeStatus::SUCCESS;
    }
  };
}  // namespace my_nav2_bt_plugin

#endif  // MY_NAV2_BT_PLUGIN__MY_CUSTOM_ACTION_NODE_HPP_
```
```
#include "my_nav2_bt_plugin/test.hpp"
#include "behaviortree_cpp_v3/bt_factory.h"

// This is the entry point that registers the plugin with BehaviorTree.CPP
BT_REGISTER_NODES(factory)
{
  factory.registerNodeType<my_nav2_bt_plugin::MyCustomAction>("MyCustomAction");
}
```
```
cmake_minimum_required(VERSION 3.5)
project(my_nav2_bt_plugin)

# Find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(nav2_behavior_tree REQUIRED)
find_package(behaviortree_cpp_v3 REQUIRED)

# Add include directories
include_directories(include)

# Create the library for the custom BT plugin
add_library(${PROJECT_NAME} SHARED src/test.cpp)

# Link against required libraries
ament_target_dependencies(${PROJECT_NAME}
  rclcpp
  nav2_behavior_tree
  behaviortree_cpp_v3
)

# Install the library and the headers
install(
  TARGETS ${PROJECT_NAME}
  LIBRARY DESTINATION lib
)

install(
  DIRECTORY include/
  DESTINATION include/${PROJECT_NAME}
)

ament_package()
```
```
bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_nav_to_pose_bt_xml: /home/bastian/Documents/own_navigation/install/gazebo_simulation/share/gazebo_simulation/xml/own_behavior_tree.xml
    bt_loop_duration: 10
    default_server_timeout: 20
    plugin_lib_names:
    - my_nav2_bt_plugin
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
```
