### ISSUE TITLE
Question on the amcl algoritm, if it is working correctly

### ISSUE THREAD

**Issue by AshBastian** [ros-navigation/docs.nav2.org#597]
Hello everybody,
I'm using ROS2 Humble with the Navigation2 Stack to move my robot around.
Everthing seem to work fine besides the Localisation from the Amcl.
It is working, to the point, where I don't get any error messages or warning from it, but the localisation is not working very well.
Here are all the parameters I use, the map and some pictures of what I mean:
```
amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.0
    alpha2: 0.0
    alpha3: 0.0
    alpha4: 0.0
    alpha5: 0.0
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field_prob"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.005
    update_min_d: 0.025
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: /map
``` 
The Map.yaml:
```
image: Map1_empty.pgm
mode: trinary
resolution: 0.05
origin: [-14.3, -14.3, 0]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.25
```
![Map1_empty](https://github.com/user-attachments/assets/86f8e942-3c77-4136-b7c9-2d149c7ec6b8)

![start_rviz](https://github.com/user-attachments/assets/fe68eb70-12dc-4904-8a23-ea8d587b5a03)
![start_gazebo](https://github.com/user-attachments/assets/2f2477d5-d48c-49d6-a7be-5c859ee45dd5)

![move_rviz](https://github.com/user-attachments/assets/1fd392c6-5e3c-4a01-9266-f62a0e678f83)
![move_gazebo](https://github.com/user-attachments/assets/b25ed39d-8f96-4f84-b626-74c252ef7afa)
